/**
 * Jingga
 *
 * @copyright Jingga
 * @license   OMS License 2.0
 * @version   1.0.0
 * @link      https://jingga.app
 */
#pragma once
#ifndef COMS_GPUAPI_ATTRIBUTE_TYPE_H
#define COMS_GPUAPI_ATTRIBUTE_TYPE_H

#include "../stdlib/Stdlib.h"

enum GpuAttributeType : byte {
    GPU_ATTRIBUTE_TYPE_VERTEX_3D,
    GPU_ATTRIBUTE_TYPE_VERTEX_3D_NORMAL,
    GPU_ATTRIBUTE_TYPE_VERTEX_3D_COLOR,
    GPU_ATTRIBUTE_TYPE_VERTEX_3D_TEXTURE_COLOR,
    GPU_ATTRIBUTE_TYPE_VERTEX_3D_SAMPLER_TEXTURE_COLOR,
    GPU_ATTRIBUTE_TYPE_VERTEX_2D_TEXTURE
};

const CONSTEXPR int32 _GPUAPI_ATTRIBUTE_COUNT[] = {
    4, // GPU_ATTRIBUTE_TYPE_VERTEX_3D
    2, // GPU_ATTRIBUTE_TYPE_VERTEX_3D_NORMAL
    2, // GPU_ATTRIBUTE_TYPE_VERTEX_3D_COLOR
    2, // GPU_ATTRIBUTE_TYPE_VERTEX_3D_TEXTURE_COLOR
    3, // GPU_ATTRIBUTE_TYPE_VERTEX_3D_SAMPLER_TEXTURE_COLOR
    2  // GPU_ATTRIBUTE_TYPE_VERTEX_2D_TEXTURE
};

#endif