/**
 * Jingga
 *
 * @copyright Jingga
 * @license   OMS License 2.0
 * @version   1.0.0
 * @link      https://jingga.app
 */
#pragma once
#ifndef COMS_MODELS_MOB_AI_STATE_H
#define COMS_MODELS_MOB_AI_STATE_H

enum MobAIState
{
    MOB_AI_STATE_IDLE,
    MOB_AI_STATE_PATROL,
    MOB_AI_STATE_INVESTIGATE,
    MOB_AI_STATE_CHASE,
    MOB_AI_STATE_MOVE_TO_TARGET,
    MOB_AI_STATE_ORBIT_TARGET,
    MOB_AI_STATE_BACK_OFF,
    MOB_AI_STATE_FLEE,
    MOB_AI_STATE_RETURN_HOME,
    MOB_AI_STATE_ENTER_COMBAT,
    MOB_AI_STATE_SELECT_TARGET,
    MOB_AI_STATE_SELECT_ABILITY,
    MOB_AI_STATE_CAST,
    MOB_AI_STATE_MELEE_ATTACK,
    MOB_AI_STATE_RECOVER,

    MOB_AI_STATE_DEAD
};

enum MobAIEvent
{
    MOB_EVENT_PLAYER_ENTERED_AGGRO,
    MOB_EVENT_PLAYER_LEFT_AGGRO,
    MOB_EVENT_TARGET_VISIBLE,
    MOB_EVENT_TARGET_LOST,
    MOB_EVENT_TOOK_DAMAGE,
    MOB_EVENT_TARGET_DIED,
    MOB_EVENT_ABILITY_FINISHED,
    MOB_EVENT_CAST_INTERRUPTED,
    MOB_EVENT_REACHED_DESTINATION,
    MOB_EVENT_LEASH_DISTANCE_EXCEEDED,
    MOB_EVENT_HEALTH_LOW,
    MOB_EVENT_RESPAWN
};

enum MobAICondition
{
    MOB_CONDITION_CAN_SEE_TARGET,
    MOB_CONDITION_CAN_HEAR_TARGET,
    MOB_CONDITION_CAN_ATTACK,
    MOB_CONDITION_TARGET_IN_MELEE,
    MOB_CONDITION_TARGET_IN_RANGE,
    MOB_CONDITION_LOW_HEALTH,
    MOB_CONDITION_HAS_MANA,
    MOB_CONDITION_IS_STUNNED,
    MOB_CONDITION_IS_SLEEPING,
    MOB_CONDITION_IS_ROOTED,
    MOB_CONDITION_IS_FEARED,
    MOB_CONDITION_IS_SILENCED,
    MOB_CONDITION_IN_DANGER,
    MOB_CONDITION_HAS_THREAT,
    MOB_CONDITION_IS_LEASHED
};

#endif