/**
 * Jingga
 *
 * @copyright Jingga
 * @license   OMS License 2.0
 * @version   1.0.0
 * @link      https://jingga.app
 */
#ifndef COMS_MODELS_NPC_CHARACTER_MOOD_H
#define COMS_MODELS_NPC_CHARACTER_MOOD_H

enum CharacterMood : byte {
    CHARACTER_MOOD_NEUTRAL = 0,
    CHARACTER_MOOD_STRESSED = 1 << 0,
    CHARACTER_MOOD_FRUSTRATED = 1 << 1,
    CHARACTER_MOOD_HAPPY = 1 << 2,
    CHARACTER_MOOD_SAD = 1 << 3,
    CHARACTER_MOOD_ANGRY = 1 << 4,
    CHARACTER_MOOD_CONFUSED = 1 << 5,
    CHARACTER_MOOD_EXCITED = 1 << 6,
    CHARACTER_MOOD_NERVOUS = 1 << 7,
    CHARACTER_MOOD_CALM = 1 << 8,
    CHARACTER_MOOD_LONELY = 1 << 9,
    CHARACTER_MOOD_ANXIOUS = 1 << 10,
    CHARACTER_MOOD_BORED = 1 << 11,
    CHARACTER_MOOD_CURIOUS = 1 << 12,
    CHARACTER_MOOD_DEPRESSED = 1 << 13,
    CHARACTER_MOOD_EMBARRASSED = 1 << 14,
    CHARACTER_MOOD_ENVIOUS = 1 << 15,
    CHARACTER_MOOD_GRATEFUL = 1 << 16,
    CHARACTER_MOOD_GUILTY = 1 << 17,
    CHARACTER_MOOD_HOPEFUL = 1 << 18,
    CHARACTER_MOOD_HORRIFIED = 1 << 19,
    CHARACTER_MOOD_INDIFFERENT = 1 << 20,
    CHARACTER_MOOD_INSPIRED = 1 << 21,
    CHARACTER_MOOD_JEALOUS = 1 << 22,
    CHARACTER_MOOD_LAZY = 1 << 23,
    CHARACTER_MOOD_MELANCHOLY = 1 << 24,
    CHARACTER_MOOD_MOTIVATED = 1 << 25,
    CHARACTER_MOOD_PARANOID = 1 << 26,
    CHARACTER_MOOD_PEACEFUL = 1 << 27,
    CHARACTER_MOOD_PROUD = 1 << 28,
    CHARACTER_MOOD_RELIEVED = 1 << 29,
    CHARACTER_MOOD_REMORSEFUL = 1 << 30,
    CHARACTER_MOOD_SARCASTIC = 1 << 31,
    CHARACTER_MOOD_SATISFIED = 1 << 32,
    CHARACTER_MOOD_SCARED = 1 << 33,
    CHARACTER_MOOD_SHY = 1 << 34,
    CHARACTER_MOOD_SKEPTICAL = 1 << 35,
    CHARACTER_MOOD_SMUG = 1 << 36,
    CHARACTER_MOOD_SURPRISED = 1 << 37,
    CHARACTER_MOOD_SYMPATHETIC = 1 << 38,
    CHARACTER_MOOD_TIRED = 1 << 39,
    CHARACTER_MOOD_VENGEFUL = 1 << 40,
    CHARACTER_MOOD_WORRIED = 1 << 41,
    CHARACTER_MOOD_ZEN = 1 << 42
};

#endif