/**
 * Jingga
 *
 * @copyright Jingga
 * @license   OMS License 2.0
 * @version   1.0.0
 * @link      https://jingga.app
 */
#ifndef COMS_MODELS_INTERACTABLE_TYPE_H
#define COMS_MODELS_INTERACTABLE_TYPE_H

#include "../../stdlib/Stdlib.h"

// The following flags describe when something is interactable
enum InteractableType : uint8 {
    INTERACTABLE_TYPE_WHILE_MOVING,
    INTERACTABLE_TYPE_WHILE_WALKING,
    INTERACTABLE_TYPE_WHILE_SWIMMING,
    INTERACTABLE_TYPE_WHILE_FALLING,
    INTERACTABLE_TYPE_WHILE_FLYING,
    INTERACTABLE_TYPE_STATIONARY,
    INTERACTABLE_TYPE_MOUNTED,
    INTERACTABLE_TYPE_RIDING_OBJECT, // e.g. on train

    INTERACTABLE_TYPE_DURING_CASTING,
    INTERACTABLE_TYPE_DURING_OTHER_ACTION,

    INTERACTABLE_TYPE_IN_WATER,
    INTERACTABLE_TYPE_OUT_OF_WATER,
    INTERACTABLE_TYPE_IN_BATTLE,
    INTERACTABLE_TYPE_OUT_OF_BATTLE,

    INTERACTABLE_TYPE_IN_PROTECTED_ZONE,
    INTERACTABLE_TYPE_OUT_OF_PROTECTED_ZONE,
    INTERACTABLE_TYPE_DURING_QUEST,
    INTERACTABLE_TYPE_OUT_OF_QUEST,
    INTERACTABLE_TYPE_IN_DUNGEON, // incl. raid etc.

    INTERACTABLE_TYPE_DUEL,
    INTERACTABLE_TYPE_OPEN_WORLD_PVP,
    INTERACTABLE_TYPE_PVP,
};

#endif